baseURL: 'https://blog.zespre.com/'
languageCode: 'en-us'
title: "Zespre's Blog"
theme: 'nostyleplease'
copyright: 'Zespre Chang'
permalinks:
  page:
    posts: '/:slug'
  section:
    posts: '/archives'
enableEmoji: true
enableRobotsTXT: true
params:
  description: >
    A real sysadmin doesn't have colleagues, only enemies.
  theme_config:
    appearance: 'auto'
    back_home_text: '..'
    date_format: '2006-01-02'
    show_description: true
  version: 'dev'
security:
  funcs:
    getenv:
    - ^HUGO_
    - ^CF_
uglyURLs: true
