baseURL: 'https://blog.zespre.com/'
languageCode: 'en-us'
title: "Zespre's Blog"
theme: 'nostyleplease'
copyright: 'Zespre Chang'
permalinks:
  page:
    posts: '/:slug'
  section:
    posts: '/archives'
enableEmoji: true
enableRobotsTXT: true
params:
  author:
    email: starbops@zespre.com
    name: 'Zespre Chang'
  description: >
    A real sysadmin doesn't have colleagues, only enemies.
  theme_config:
    appearance: 'auto'
    back_home_text: '..'
    date_format: '2006-01-02'
    show_description: true
  version: 'v2.2.1'
  commit: ''
security:
  funcs:
    getenv:
    - ^HUGO_
    - ^CF_
outputs:
  home:
  - html
  - rss
  section:
  - html
  - rss
  taxonomy:
  - html
  term:
  - html