kind: pipeline
type: kubernetes
name: default
steps:
- name: lint
  image: ruby:2.7.1-buster
  commands:
  - gem install mdl
  - mdl README.md
- name: build on tag
  image: plugins/docker
  settings:
    registry: registry.internal.zespre.com
    repo: registry.internal.zespre.com/starbops/blog
    tags:
    - ${DRONE_TAG##v}-${DRONE_COMMIT_SHA:0:7}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  build_args:
  - JEKYLL_ENV=production
  when:
    event:
    - tag
- name: build on push
  image: plugins/docker
  settings:
    registry: registry.internal.zespre.com
    repo: registry.internal.zespre.com/starbops/blog
    tags:
    - latest
    - ${DRONE_COMMIT_SHA:0:7}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  build_args:
  - JEKYLL_ENV=development
  when:
    event:
    - push
- name: deploy
  image: bitsbeats/drone-helm3
  settings:
    kube_api_server:
      from_secret: kube_api_server
    kube_token:
      from_secret: kube_token
    chart: zpcc/blog
    release: blog
    namespace: blog-test
    timeout: 5
    helm_repos:
    - zpcc=https://charts.internal.zespre.com
    values:
    - image.tag=${DRONE_TAG##v}-${DRONE_COMMIT_SHA:0:7}
    - imagePullSecrets[0].name=regcred
  when:
    event:
    - tag
- name: notification
  image: plugins/slack
  settings:
    webhook: https://mattermost.internal.zespre.com/hooks/d1ymz9ie3fyrudk76qon6hc4dr
    channel: cicd
    username: drone-bot
    icon_url: https://pbs.twimg.com/profile_images/1291040329395613698/bpYKcF66_400x400.jpg
  when:
    status:
    - success
    - failure
