kind: pipeline
type: kubernetes
name: default
steps:
- name: lint
  image: ruby:2.7.1-buster
  commands:
  - gem install mdl
  - mdl blog/*.md blog/_posts/*.md
- name: build on tag
  image: plugins/docker
  settings:
    mtu: 1450
    registry: registry.internal.zespre.com
    repo: registry.internal.zespre.com/starbops/blog
    tags:
    - ${DRONE_TAG##v}-${DRONE_COMMIT_SHA:0:7}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    build_args:
    - JEKYLL_ENV=production
    - VERSION=${DRONE_TAG##v}-${DRONE_COMMIT_SHA:0:7}
  when:
    event:
    - tag
- name: build on push
  image: plugins/docker
  settings:
    mtu: 1450
    registry: registry.internal.zespre.com
    repo: registry.internal.zespre.com/starbops/blog
    tags:
    - latest
    - ${DRONE_COMMIT_SHA:0:7}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    build_args:
    - JEKYLL_ENV=development
    - VERSION=${DRONE_COMMIT_SHA:0:7}
  when:
    event:
    - push
- name: deploy to staging
  image: bitsbeats/drone-helm3
  settings:
    kube_api_server:
      from_secret: kube_api_server
    kube_token:
      from_secret: kube_token_staging
    kube_skip_tls: true
    lint: false
    build_dependencies: false
    chart: zpcc/blog
    release: blog
    namespace: blog-staging
    timeout: 5m
    helm_repos:
    - zpcc=https://charts.internal.zespre.com
    envsubst: true
    values:
    - image.tag=${DRONE_COMMIT_SHA:0:7}
    - imagePullSecrets[0].name=regcred
  when:
    event:
    - push
    branch:
    - master
- name: deploy to prod
  image: bitsbeats/drone-helm3
  settings:
    kube_api_server:
      from_secret: kube_api_server
    kube_token:
      from_secret: kube_token_prod
    kube_skip_tls: true
    lint: false
    build_dependencies: false
    chart: zpcc/blog
    release: blog
    namespace: blog-prod
    timeout: 5m
    helm_repos:
    - zpcc=https://charts.internal.zespre.com
    envsubst: true
    values:
    - image.tag=${DRONE_TAG##v}-${DRONE_COMMIT_SHA:0:7}
    - imagePullSecrets[0].name=regcred
    - ingress.enabled=true
    - ingress.annotations.kubernetes\\.io/ingress\\.class=nginx-cloud
    - ingress.annotations.cert-manager\\.io/cluster-issuer=letsencrypt-prod-cloud
    - ingress.hosts[0].host=blog.zespre.com
    - ingress.hosts[0].paths[0].path="/"
    - ingress.tls[0].hosts[0]=blog.zespre.com
    - ingress.tls[0].secretName=blog-tls
  when:
    event:
    - tag
- name: notification
  image: plugins/slack
  settings:
    webhook: https://mattermost.internal.zespre.com/hooks/d1ymz9ie3fyrudk76qon6hc4dr
    channel: cicd
    username: drone-bot
    icon_url: https://pbs.twimg.com/profile_images/1291040329395613698/bpYKcF66_400x400.jpg
  when:
    status:
    - success
    - failure
