---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blog-tls
  namespace: blog-universal
spec:
  secretName: blog-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: blog.zespre.com
  dnsNames:
  - blog.zespre.com
