---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  namespace: blog-universal
spec:
  selector:
    matchLabels:
      app: blog
  replicas: 3
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: registry.internal.zespre.com/zpcc-blog:0.11.0
        ports:
        - containerPort: 80
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 60
        readinessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 30
      imagePullSecrets:
      - name: regcred
