title: Zespre's Blog
author: Zespre Schmidt
email: starbops@zespre.com
url: https://blog.zespre.com
baseurl: ''
description: >
  Know Now

permalink: /:slug.html

favicon: 'logo.png'

theme: no-style-please

theme_config:
  appearance: auto
  back_home_text: '..'
  date_format: '%Y-%m-%d'
  show_description: false

sass:
  style: :compressed

plugins:
- jekyll-feed
- jekyll-seo-tag
