collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

google_analytics: UA-56544554-1

plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
