source 'https://rubygems.org'

gem 'jekyll', '3.9.0'
gem 'kramdown-parser-gfm'
gem 'no-style-please', '0.4.7'

group :jekyll_plugins do
  gem 'jekyll-feed'
  gem 'jekyll-seo-tag'
  gem 'jekyll-sitemap'
  gem 'jemoji'
end
