name: Pull Request Build

on:
  pull_request:
    types:
    - opened
    - synchronize

jobs:
  build-pr:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: '0.131.0'
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: ${{ env.HUGO_VERSION }}
        extended: true
    - name: Lint
      run: make lint
    - name: Build
      run: hugo --minify
