name: Build and Publish

on:
  push:
    branches:
    - main
    - release
    tags:
    - v*

env:
  HUGO_VERSION: 0.131.0
  NGINX_VERSION: 1.27.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: starbops/blog
    - name: Docker build and push
      uses: docker/build-push-action@v6
      with:
        provenance: false
        context: .
        platforms: linux/amd64,linux/arm64
        build-args: |
          HUGO_VERSION=$HUGO_VERSION
          NGINX_VERSION=$NGINX_VERSION
          VERSION=${{ github.ref_name }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
